FillValue for PARAM
OceanGlidersCommunity/OG-format-user-manual pull request #114
Opened 2022-09-21 18:22 UTC by vturpin

Following recommendation of #102 to clarify how to manage fix values

Proponents: 
Moderator: @OceanGlidersCommunity/format-mantainers

# Type of PR

- [ ] Typo without possible change of interpretation of the related text.
- [ ] Fix of some error, inconsistency, unforeseen limitation.
- [ ] Style that only affects visually the compiled document
- [X] Addition that does not require change in the current structure.
- [ ] Enhancement that require changes to improve the format.

# Related Issues

# Dates when it got review approvals

The suggestion made by @castelao has been made a month ago. 
So I push a PR to close the issue

# Release checklist

- [ ] Approved by at least two members of the committee?
- [ ] There were modifications after the review approvals? If so, please
      ask reviewers to update their review.
- [ ] Proponents and moderador should explicitly agree that it is ready to
      to merge.
- [ ] The moderador is the one in charge to actually merge or close this PR
      according to the final decision.

# For maintainers

- [ ] Update the moderator with a volunteer from the committee. It would be
      best to have one single moderator to guide and help this PR to move
      forward. It is OK to update the moderador pass it to another one.
- [ ] Confirm that the associated branch was deleted after the merging.
- [ ] Wrap-up and close the related issues.

# Comments

2022-09-22 16:09 UTC, castelao commented on OG_Format.adoc
> +"We recommend using NaN for float/double, but the user is allowed to choose any value with the same data type of the variable."
Maybe add a reminder that this value should be out of that sensor's range of possible measurements? I know it should be obvious, but it won't hurt to be explicit.

I'm OK if you think it is too much.

2022-09-22 16:09 UTC, castelao approved these changes

2023-04-24 13:59 UTC, justinbuck requested changes
Discussed at OG 1.0 meeting 24th April 2023, is inconstant with geophysical variables section.
Updated recommendation based on feedback needed.

2023-04-24 14:23 UTC, callumrollo approved these changes

2023-04-24 14:24 UTC, justinbuck approved these changes
Approved by consensus at OG 1.0 meeting 24th April 2023

2023-04-24 14:25 UTC, merged