Moving examples to an appendix
OceanGlidersCommunity/OG-format-user-manual pull request #32
Opened 2021-10-04 05:19 UTC by castelao

Keep the document clean and short.

On the top of the example files, we should add plenty of examples in the document to help the reader, such as the ones added by @vturpin. To avoid a way too long document, what about collecting the examples in the appendix?

2021-10-04 06:10 UTC, soerenthomsen requested changes
For me it makes sense to move the examples into the appendix. Although one example might be helpful upfront? 

When working on these examples it makes sense to make them congruent. 
i.e. for example 1 "=" is used and for the next ones " : ". Should be the same for all examples.

See comments directly in the text

2021-10-04 06:13 UTC, soerenthomsen requested changes

2021-10-04 06:13 UTC, soerenthomsen commented on OG_Format.adoc
> +* platform (i.e. glider mission) = kraken_20210205
here we write " ... = ... "

2021-10-04 06:13 UTC, soerenthomsen commented on OG_Format.adoc
> +* Programme : SOCIB Glider Programme
Here ". : ." 

If we decide to use ":" each time the space before : should be removed

i.e. everywhere
```suggestion
* Programme: SOCIB Glider Programme
```

2021-10-04 08:33 UTC, justinbuck requested changes
Does the main body of the document introduce the examples and reference the appendix

2021-10-04 18:37 UTC, castelao commented
This PR is related to #26 , which might require some changes on the examples listed here.

2021-10-04 23:01 UTC, justinbuck approved these changes
requested changes added, approving

2021-10-05 08:05 UTC, soerenthomsen approved these changes

2021-10-05 08:06 UTC, merged