add thre .cdl files
OceanGlidersCommunity/OG-format-user-manual pull request #86
Opened 2022-07-26 22:21 UTC by vturpin

"netcdf sp041_20191205T1757_V3.lua" : Third version of the current proto (Variable option) - Aiming to be fully compliant with current version of the format.
"netcdf_sp041_20191205T1757._encapsulate1.cdl.lua" : one possible version of the proto .cdl (attribute version) - Aiming to be compliant with the format but integrating the "attribute vs variable" issue.
"netcdf_sp041_20191205T1757._encapsulate2.cdl.lua" : one other possible version of the proto .cdl (encapsulate version) ; Aiming to be compliant with the format but integrating the "attribute vs variable" issue.

2022-08-16 08:56 UTC, callumrollo approved these changes
Looks good to me. I think the encapsulate1(attributes) version would be best to converge on going forward

2022-08-16 17:59 UTC, castelao commented
Let's explore this in parts. Let me check if I got it right. The two new proposed files (encapsulated) transfer the `PLATFORM` information to attributes of a single variable named `PLATFORM_INFORMATION`? Is that correct?

If this is correct, there is no value on the information stored in the actual variable and no need to use the dimension associated with that variable. Correct? As it is, or the two proposed modifications don't allow aggregation of multiple platforms anyways, so let's forget about aggregation for a moment. This means this file would store one single platform. Thus, I don't see a reason why not to upgrade those `PLATFORM_INFORMATION` attributes to global attributes. It does increase the global attributes list, but the current and the two proposed files add some unnecessary information.

In summary, I suggest removing `PLATFORM_INFORMATION`, `PLATFORM_TYPE`, `PLATFORM_MODEL`, ... and transferring this information to global variables.

The global attributes, with an example value, would be:

- platform_type = "sub-surface gliders";
- platform_type_vocabulary = "http://vocab.nerc.ac.uk/collection/OGXXX/";
- platform_model = "spray";
- platform_model_vocabulary = "http://vocab.nerc.ac.uk/collection/OGXXX/";
- platform_maker = "Scripps Institution of Oceanography";
- platform_maker_vocabulary = "http://vocab.nerc.ac.uk/collection/OGXXX/";
- wmo_identifier = "4801948"; 
- platform_serial_number = "41";
- platform_code = "sp41";
- platform_depth_ranking = "1000m";
- ices_code = "";

The main benefit as it is now would be the possibility to extend a new dimension 'platform', allowing multiple values directly mapped. Without the purpose of allowing aggregation, it is better to elevate those `PLATFORM_INFORMATION:platform_*` to global attributes.

2022-08-16 18:04 UTC, castelao requested changes
It is convenient to use a PR and show the examples, but it can't be merged as it is. I'm blocking it here so we don't merge it by mistake.

2022-08-17 08:24 UTC, vturpin commented
Sure no need to merge at this point. It would be too confusing.
_Let's explore this in parts. Let me check if I got it right. The two new proposed files (encapsulated) transfer the PLATFORM information to attributes of a single variable named PLATFORM_INFORMATION? Is that correct?_
Yes

More generaly, do you consider that unlike PLATFORM_INFORMATION, HARDWARE_INFORMATION, SENSOR_INFORMATION, etc. ... should go in the global attribute section ?
My feeling is that is we put everything in global attribute the file will become extremely messy.

2022-08-17 16:16 UTC, castelao commented
@vturpin , `SENSOR_INFORMATION` is a different story because we can have one or more sensors. I'm working on a suggestion to address that.

2024-02-12 11:05 UTC, vturpin commented
This PR is not relevant anymore.
No need for three proto.cdl files.
I close the PR.

2024-02-12 11:05 UTC, closed without merging