build docs on push to main
OceanGlidersCommunity/OG-format-user-manual pull request #99
Opened 2022-08-22 08:19 UTC by callumrollo

This will automatically build the documentation site when a push is made to the main branch, keeping the docs up to date

2022-08-22 09:38 UTC, vturpin approved these changes
Even though I do not understand the role of this two lines ;) I agree on the principle of automation.

2022-08-22 15:27 UTC, castelao requested changes

2022-08-22 15:27 UTC, castelao commented on .github/workflows/adoc_build.yml
> -  workflow_dispatch:
I suggest keeping this one together with push. I found it useful when developing to be able to recompile it manually. By keeping both, we expect to have the auto mode on daily activities.

2022-08-22 15:32 UTC, castelao commented
@callumrollo. thanks !

@vturpin , you raised a very important issue, the versioning control. Since we don't have a stable full version yet, I think it is OK to keep moving along as we've been doing. We need to move efficiently now. Once we are getting closer to a stable version, we shall define a clear protocol. There are many ways of doing that. Let's save this discussion for later, but don't forget about it.

2022-08-23 06:51 UTC, callumrollo commented
Yes, some versioning will ikely be needed down the line. Especially once the format is in production and we may have multiple versions. This should do for now though

2022-08-23 13:37 UTC, castelao approved these changes

2022-08-23 13:38 UTC, merged